### ISSUE TITLE
Disable getters for specific fields

### ISSUE THREAD

**Issue by Kriskras99** [sigp/superstruct#43]
It would be useful to disable the generating of getters for when variants have the same field but a different type:
```Rust
#[superstruct(variants(V1, V2))]
pub struct Example {
    #[superstruct(only(V1))
    pub field: String,
    #[superstruct(only(V2))
    pub field: usize,
}
```
This does not compile as it will generate two getter functions.

Something like this would make it possible:
```Rust
#[superstruct(variants(V1, V2))]
pub struct Example {
    #[superstruct(only(V1), no_getter)
    pub field: String,
    #[superstruct(only(V2), no_getter)
    pub field: usize,
}
```

**Comment by michaelsproul** [comment]
There's a workaround for this at the moment using `rename`. You can rename the getters so that they don't collide. There's an example of this in the book under the `Flatten` section: https://sigp.github.io/superstruct/config/field.html#flatten

**Comment by michaelsproul** [comment]
I think an option to disable getters entirely would be good though
